# Generated by Django 6.0.1 on 2026-01-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_page', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
